### ISSUE TITLE
One on one chat window doesn't always open

### ISSUE THREAD

**Issue by beechannels** [beechannels/beechat#1]
refreshing the page is sometimes needed to see a new chat window properly, ie the one being talked to needs to refresh the page before being able to see someone else is trying to chat.

**Comment by tdxdave** [comment]
I am seeing this with the https://github.com/downloads/beechannels/beechat/beechannels-beechat-v0.4.zip download.

**Comment by tdxdave** [comment]
If this was fixed in the source can you please refer me to the commit? I downloaded the latest from the git repository but this stll does not pop up the chat window.
