### ISSUE TITLE
authentication using external entity 

### ISSUE THREAD

**Issue by siskap** [beechannels/beechat#11]
First of all I would like to thank you for your work on the beechat!

I have found a problem when trying to log in to beechat using an external jabber chat client. Any person is allowed to log in. Have traced the problem down to the ejabberd_elgg_auth.pl line 136 that has an additional result=1 before exiting the funtion(I have added a comment to the line bellow) 
# 
# External authentication
# 

sub auth_ext {
    my($user, $password) = @_;
    my $result = 0;

```
my $sql = qq/SELECT salt FROM $db_table WHERE $field_user = ?;/;
my $sth = $dbh->prepare($sql);

$sth->bind_param(1, $user);
$sth->execute()
or die DBI->errstr;

my @res = $sth->fetchrow_array();
$sth->finish;
if (!$res[0]) {
$result = 0;
} else {
$sql = qq/SELECT COUNT(*) FROM $db_table WHERE $field_user = ? AND $field_password = MD5(CONCAT(?, ?));/;
$sth = $dbh->prepare($sql);

$sth->bind_param(1, $user);
$sth->bind_param(2, $password);
$sth->bind_param(3, $res[0]);
$sth->execute()
    or die DBI->errstr;

my @count = $sth->fetchrow_array();
$sth->finish;
$result = $count[0] || 0;
}
```

$result = 1;                   ###! siskap: This line of code should not be here
    return ($result);

When this line is deleted the script works ok.

Regards,
Petr

**Comment by beechannels** [comment]
Thank Petr, We've fixed this issue.
