### ISSUE TITLE
unable to find chat window 

### ISSUE THREAD

**Issue by bhgraham** [beechannels/beechat#3]
i already had ejabberd installed and integrated with elgg, but i like your approach so i have modified my setup to be like yours.  Ejabberd connects ok with the auth script for external clients, but when i log into the elgg site I don't see any sort of client for xmpp.

**Comment by hayaza** [comment]
Yup, same with me, no xmpp client visible in elgg.

**Comment by beechannels** [comment]
this plugin was checking if you have friends to display the chat bar. He didn't do it anymore. The chat bar shows up even if you don't have any friend
